b:
	./gradlew b
op:
	./gradlew op
clean-build:
	./gradlew clean build
clean-op:
	./gradlew clean build optimizeJar
clean-op-stacktrace:
	./gradlew clean build optimizeJar --stacktrace
test:
	./gradlew test
